version: '2'

services:
  website:
    build: .
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/backend_top_rated_app'
    ports:
      - '${PORT}:${PORT}'
    entrypoint: "gunicorn -b 0.0.0.0:${PORT} --access-logfile - 'app:app'"
    depends_on:
      - "postgres"
  postgres:
    image: 'postgres:14.2'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

volumes:
  postgres: