version: '2'

services:
  pycharm:
    build: .
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/backend_top_rated_app'
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - "postgres"
  postgres:
    image: 'postgres:14.2'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
volumes:
  postgres: